# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: showtime.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eshowtime.proto\"0\n\x0cScheduleData\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x12\n\nMovieDatas\x18\x02 \x03(\t\"\x14\n\x04\x44\x61te\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2`\n\x08Showtime\x12)\n\x0cGetShowTimes\x12\x06.Empty\x1a\r.ScheduleData\"\x00\x30\x01\x12)\n\x0fGetMoviesByDate\x12\x05.Date\x1a\r.ScheduleData\"\x00\x62\x06proto3')



_SCHEDULEDATA = DESCRIPTOR.message_types_by_name['ScheduleData']
_DATE = DESCRIPTOR.message_types_by_name['Date']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
ScheduleData = _reflection.GeneratedProtocolMessageType('ScheduleData', (_message.Message,), {
  'DESCRIPTOR' : _SCHEDULEDATA,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:ScheduleData)
  })
_sym_db.RegisterMessage(ScheduleData)

Date = _reflection.GeneratedProtocolMessageType('Date', (_message.Message,), {
  'DESCRIPTOR' : _DATE,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:Date)
  })
_sym_db.RegisterMessage(Date)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

_SHOWTIME = DESCRIPTOR.services_by_name['Showtime']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCHEDULEDATA._serialized_start=18
  _SCHEDULEDATA._serialized_end=66
  _DATE._serialized_start=68
  _DATE._serialized_end=88
  _EMPTY._serialized_start=90
  _EMPTY._serialized_end=97
  _SHOWTIME._serialized_start=99
  _SHOWTIME._serialized_end=195
# @@protoc_insertion_point(module_scope)
