# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: booking.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\"\x0e\n\x0c\x45mptyBooking\"&\n\x17\x41\x64\x64\x42ookingReturnMessage\x12\x0b\n\x03msg\x18\x01 \x01(\t\"D\n\x13\x41\x64\x64\x42ookingParameter\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x0f\n\x07movieid\x18\x03 \x01(\t\"7\n\x0b\x42ookingData\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x18\n\x05\x64\x61tes\x18\x02 \x03(\x0b\x32\t.DateData\"(\n\x08\x44\x61teData\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"\x18\n\x06UserId\x12\x0e\n\x06userid\x18\x01 \x01(\t2\xa7\x01\n\x07\x42ooking\x12>\n\nAddBooking\x12\x14.AddBookingParameter\x1a\x18.AddBookingReturnMessage\"\x00\x12-\n\nGetBooking\x12\r.EmptyBooking\x1a\x0c.BookingData\"\x00\x30\x01\x12-\n\x12GetBookingByUserId\x12\x07.UserId\x1a\x0c.BookingData\"\x00\x62\x06proto3')



_EMPTYBOOKING = DESCRIPTOR.message_types_by_name['EmptyBooking']
_ADDBOOKINGRETURNMESSAGE = DESCRIPTOR.message_types_by_name['AddBookingReturnMessage']
_ADDBOOKINGPARAMETER = DESCRIPTOR.message_types_by_name['AddBookingParameter']
_BOOKINGDATA = DESCRIPTOR.message_types_by_name['BookingData']
_DATEDATA = DESCRIPTOR.message_types_by_name['DateData']
_USERID = DESCRIPTOR.message_types_by_name['UserId']
EmptyBooking = _reflection.GeneratedProtocolMessageType('EmptyBooking', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYBOOKING,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:EmptyBooking)
  })
_sym_db.RegisterMessage(EmptyBooking)

AddBookingReturnMessage = _reflection.GeneratedProtocolMessageType('AddBookingReturnMessage', (_message.Message,), {
  'DESCRIPTOR' : _ADDBOOKINGRETURNMESSAGE,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:AddBookingReturnMessage)
  })
_sym_db.RegisterMessage(AddBookingReturnMessage)

AddBookingParameter = _reflection.GeneratedProtocolMessageType('AddBookingParameter', (_message.Message,), {
  'DESCRIPTOR' : _ADDBOOKINGPARAMETER,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:AddBookingParameter)
  })
_sym_db.RegisterMessage(AddBookingParameter)

BookingData = _reflection.GeneratedProtocolMessageType('BookingData', (_message.Message,), {
  'DESCRIPTOR' : _BOOKINGDATA,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:BookingData)
  })
_sym_db.RegisterMessage(BookingData)

DateData = _reflection.GeneratedProtocolMessageType('DateData', (_message.Message,), {
  'DESCRIPTOR' : _DATEDATA,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:DateData)
  })
_sym_db.RegisterMessage(DateData)

UserId = _reflection.GeneratedProtocolMessageType('UserId', (_message.Message,), {
  'DESCRIPTOR' : _USERID,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:UserId)
  })
_sym_db.RegisterMessage(UserId)

_BOOKING = DESCRIPTOR.services_by_name['Booking']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTYBOOKING._serialized_start=17
  _EMPTYBOOKING._serialized_end=31
  _ADDBOOKINGRETURNMESSAGE._serialized_start=33
  _ADDBOOKINGRETURNMESSAGE._serialized_end=71
  _ADDBOOKINGPARAMETER._serialized_start=73
  _ADDBOOKINGPARAMETER._serialized_end=141
  _BOOKINGDATA._serialized_start=143
  _BOOKINGDATA._serialized_end=198
  _DATEDATA._serialized_start=200
  _DATEDATA._serialized_end=240
  _USERID._serialized_start=242
  _USERID._serialized_end=266
  _BOOKING._serialized_start=269
  _BOOKING._serialized_end=436
# @@protoc_insertion_point(module_scope)
